# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/api.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_ApiKey(object):
    def setupUi(self, Dialog_ApiKey):
        Dialog_ApiKey.setObjectName("Dialog_ApiKey")
        Dialog_ApiKey.resize(600, 90)
        Dialog_ApiKey.setMinimumSize(QtCore.QSize(0, 90))
        Dialog_ApiKey.setMaximumSize(QtCore.QSize(16777215, 90))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_ApiKey)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_ApiKey)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox_key = QtWidgets.QComboBox(Dialog_ApiKey)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_key.sizePolicy().hasHeightForWidth())
        self.comboBox_key.setSizePolicy(sizePolicy)
        self.comboBox_key.setEditable(True)
        self.comboBox_key.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboBox_key.setObjectName("comboBox_key")
        self.verticalLayout.addWidget(self.comboBox_key)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_clean_apikey = QtWidgets.QPushButton(Dialog_ApiKey)
        self.pushButton_clean_apikey.setObjectName("pushButton_clean_apikey")
        self.horizontalLayout.addWidget(self.pushButton_clean_apikey)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_ApiKey)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_ApiKey)
        self.buttonBox.accepted.connect(Dialog_ApiKey.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_ApiKey.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_ApiKey)

    def retranslateUi(self, Dialog_ApiKey):
        _translate = QtCore.QCoreApplication.translate
        Dialog_ApiKey.setWindowTitle(_translate("Dialog_ApiKey", "Dialog"))
        self.label.setText(_translate("Dialog_ApiKey", "please enter your OPENAI API KEY or encrypt chain code"))
        self.comboBox_key.setPlaceholderText(_translate("Dialog_ApiKey", "please enter your OPENAI API KEY or encrypt chain code"))
        self.pushButton_clean_apikey.setText(_translate("Dialog_ApiKey", "Clean"))
